language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
            - george-edison55-precise-backports
          packages:
            - g++-7
            - clang-5.0
            - cmake-data
            - cmake 
      env:
        - MATRIX_EVAL1="CC=gcc-7 && CXX=g++-7"
        - MATRIX_EVAL2="CC=clang-5.0 && CXX=clang++-5.0"
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL3="CC=gcc-4.9 && CXX=g++-4.9"
    - os: osx
      osx_image: xcode10.1

before_install:
  - eval "${MATRIX_EVAL1}"
  - eval "${MATRIX_EVAL2}"
  - eval "${MATRIX_EVAL3}"

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
